pluginManagement {
    includeBuild('build-logic')
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
}

include ':kydra-log-manual'
project(':kydra-log-manual').projectDir = new File(settingsDir, './library/')

include ':kydra-log'
project(':kydra-log').projectDir = new File(settingsDir, './plug-and-play/')

// Common
include ':example'
include ':example:common'
include ':example:android'
include ':example:js'
