[versions]
kotlin            = "2.3.10"
android-gradle    = "8.13.0"
constraint-layout = "2.0.4"
nmcp              = "1.4.4"

[libraries]
kotlin-stdlib             = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib",        version.ref = "kotlin" }
kotlin-test               = { group = "org.jetbrains.kotlin", name = "kotlin-test",          version.ref = "kotlin" }
kotlin-test-js            = { group = "org.jetbrains.kotlin", name = "kotlin-test-js",       version.ref = "kotlin" }
kotlin-gradle-plugin      = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin     = { group = "com.android.tools.build", name = "gradle",            version.ref = "android-gradle" }
android-constraint-layout = { group = "com.android.support.constraint", name = "constraint-layout", version.ref = "constraint-layout" }

[plugins]
android-application  = { id = "com.android.application",           version.ref = "android-gradle" }
android-library      = { id = "com.android.library",               version.ref = "android-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android       = { id = "org.jetbrains.kotlin.android",       version.ref = "kotlin" }
nmcp                 = { id = "com.gradleup.nmcp",                  version.ref = "nmcp" }
nmcp-aggregation     = { id = "com.gradleup.nmcp.aggregation",      version.ref = "nmcp" }
