[versions]
kotlin            = "2.3.10"
android-gradle    = "8.13.0"
constraint-layout = "2.0.4"

[libraries]
kotlin-stdlib             = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib",        version.ref = "kotlin" }
kotlin-test               = { group = "org.jetbrains.kotlin", name = "kotlin-test",          version.ref = "kotlin" }
kotlin-test-js            = { group = "org.jetbrains.kotlin", name = "kotlin-test-js",       version.ref = "kotlin" }
android-constraint-layout = { group = "com.android.support.constraint", name = "constraint-layout", version.ref = "constraint-layout" }

[plugins]
android-application  = { id = "com.android.application",           version.ref = "android-gradle" }
android-library      = { id = "com.android.library",               version.ref = "android-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android       = { id = "org.jetbrains.kotlin.android",       version.ref = "kotlin" }
